/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Position = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const PlayerState = IDL.Record({
  'score' : IDL.Nat,
  'position' : Position,
  'health' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllPlayers' : IDL.Func([], [IDL.Vec(PlayerState)], ['query']),
  'getPlayerState' : IDL.Func([], [PlayerState], ['query']),
  'spawnPlayer' : IDL.Func([Position], [], []),
  'takeDamage' : IDL.Func([IDL.Int], [], []),
  'updatePosition' : IDL.Func([Position], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Position = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const PlayerState = IDL.Record({
    'score' : IDL.Nat,
    'position' : Position,
    'health' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllPlayers' : IDL.Func([], [IDL.Vec(PlayerState)], ['query']),
    'getPlayerState' : IDL.Func([], [PlayerState], ['query']),
    'spawnPlayer' : IDL.Func([Position], [], []),
    'takeDamage' : IDL.Func([IDL.Int], [], []),
    'updatePosition' : IDL.Func([Position], [], []),
  });
};

export const init = ({ IDL }) => { return []; };